name: 🏗️ Build and ✅ Test

on:
  push:
    branches:
      - main
      - initial-create
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild /p:Configuration=Release

    - name: Setup VSTest.console.exe
      uses: darenm/Setup-VSTest@v1

    - name: Run NUnit Tests
      run: |
        Get-ChildItem -Path "${{ github.workspace }}\src" -Recurse -Filter '*Tests.dll' | ForEach-Object {
          & "vstest.console.exe" "$($_.FullName)"
        }
      shell: pwsh