name: 🏗️ Build and ✅ Test

on:
  push:
    branches:
      - main
      - initial-create
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore NuGet packages
      run: nuget restore

    - name: Build solution
      run: msbuild /p:Configuration=Release

    - name: Run tests
      run: |
        vstest.console.exe **\*Tests*.dll