name: 🏗️ Build and ✅ Test

on:
  push:
    branches:
      - main
      - initial-create
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  label:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.base_ref != 'main' }}
    permissions: write-all
    name: "🏷️ Label PR"
    steps:
      - name: 🏷️ Label PR with automerge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              issue_number: context.payload.pull_request.number,
              labels: ['automerge']
            });
  build:
    runs-on: windows-latest
    name: "🏗️ Build and ✅ Test"
    timeout-minutes: 10

    steps:
    - name: 🛒 Checkout code
      uses: actions/checkout@v2

    - name: 🛠️ Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: 🔨 Install Dependencies
      run: nuget restore

    - name: 🏭 Build
      run: msbuild /p:Configuration=Release

    - name: 👀 Setup Test Runner
      uses: darenm/Setup-VSTest@v1

    - name: ✅ Unit Tests
      run: |
        Get-ChildItem -Path "${{ github.workspace }}\src" -Recurse -Filter '*Tests.dll' | ForEach-Object {
          & "vstest.console.exe" "$($_.FullName)"
        }
      shell: pwsh
